Make credentials secret required
The controller pods should not start until a secret with AWS credentials is
present.

With this patch, controller pods are in CreateContainerConfigError state with
this event until the secret is present:

    Error: secret "aws-cloud-credentials" not found